apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-vehicle-service-config
data:
  SERVER_PORT: "3001"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: "customer-vehicle-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
